<?php
/**
 * Generate Full AI Visibility PDF Report
 * Called by webhook.php after Stripe payment
 * Returns: path to generated PDF file
 */

require_once __DIR__ . '/fpdf.php';

function generateFullReport($domain) {
    // Run audit
    $audit = runAudit($domain);
    if (!$audit) return null;
    
    $pdf = new FPDF();
    $pdf->SetAutoPageBreak(true, 20);
    
    // ═══ COVER PAGE ═══
    $pdf->AddPage();
    $pdf->Rect(0, 0, 210, 297, 'F'); // Dark bg
    $pdf->SetFillColor(9, 9, 11);
    $pdf->Rect(0, 0, 210, 297, 'F');
    
    // Accent line
    $grade_colors = ['A'=>[52,211,153], 'B'=>[96,165,250], 'C'=>[251,191,36], 'D'=>[251,146,60], 'F'=>[248,113,113]];
    $gc = $grade_colors[$audit['grade']] ?? [255,255,255];
    $pdf->SetFillColor($gc[0], $gc[1], $gc[2]);
    $pdf->Rect(20, 80, 170, 2, 'F');
    
    // Title
    $pdf->SetTextColor(255, 255, 255);
    $pdf->SetXY(20, 90);
    $pdf->SetFont('Arial', 'B', 32);
    $pdf->Cell(170, 15, 'AI Visibility Report', 0, 1);
    
    $pdf->SetXY(20, 110);
    $pdf->SetFont('Arial', '', 16);
    $pdf->SetTextColor(160, 160, 170);
    $pdf->Cell(170, 10, $domain, 0, 1);
    
    // Grade
    $pdf->SetXY(20, 135);
    $pdf->SetFont('Arial', 'B', 60);
    $pdf->SetTextColor($gc[0], $gc[1], $gc[2]);
    $pdf->Cell(170, 30, $audit['grade'], 0, 1);
    
    $pdf->SetXY(20, 170);
    $pdf->SetFont('Arial', '', 14);
    $pdf->SetTextColor(255, 255, 255);
    $pdf->Cell(170, 10, "{$audit['score']}/100", 0, 1);
    
    // Label
    $labels = [
        'A' => 'Odlicno! Vase podjetje je vidno za AI modele.',
        'B' => 'Dobro. Skoraj pripravljeno za AI priporocila.',
        'C' => 'Povprecno. Nekaj manjka — AI vas ne priporoca.',
        'D' => 'Slabo. Vase podjetje je komaj vidno za AI.',
        'F' => 'Nevidno. AI modeli ne vidijo vasega podjetja.',
    ];
    $pdf->SetXY(20, 185);
    $pdf->SetFont('Arial', '', 12);
    $pdf->SetTextColor(180, 180, 190);
    $pdf->MultiCell(170, 7, $labels[$audit['grade']] ?? '');
    
    // Footer
    $pdf->SetXY(20, 260);
    $pdf->SetFont('Arial', '', 9);
    $pdf->SetTextColor(100, 100, 110);
    $pdf->Cell(170, 5, 'Generated by AI Visibility Tool — hd-webdesign.si/ai-izkaznica/', 0, 1);
    $pdf->Cell(170, 5, date('Y-m-d H:i'), 0, 1);
    
    // ═══ PAGE 2: AI VISIBILITY CHECKS ═══
    $pdf->AddPage();
    $pdf->SetFillColor(9, 9, 11);
    $pdf->Rect(0, 0, 210, 297, 'F');
    
    $y = sectionHeader($pdf, '1. AI Visibility Checks', 20);
    
    $checks = $audit['checks'] ?? [];
    foreach ($checks as $key => $check) {
        $status = $check['pass'] ? 'PASS' : 'FAIL';
        $color = $check['pass'] ? [52,211,153] : [248,113,113];
        $y = reportItem($pdf, $check['label'], "{$status} (+{$check['points']} tock)", $y, $color);
    }
    
    // Score bar
    $y += 10;
    $pdf->SetXY(25, $y);
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->SetTextColor(255, 255, 255);
    $pdf->Cell(170, 8, "Skupaj: {$audit['score']}/100 — Ocena: {$audit['grade']}", 0, 1);
    
    // ═══ PAGE 2: TECHNICAL ANALYSIS ═══
    $y += 15;
    if ($y > 250) { $pdf->AddPage(); $pdf->SetFillColor(9,9,11); $pdf->Rect(0,0,210,297,'F'); $y = 20; }
    
    $y = sectionHeader($pdf, '2. Technical Analysis', $y);
    
    $tech = $audit['technical'] ?? [];
    $y = reportItem($pdf, 'CMS', $tech['cms'] ?? 'unknown', $y);
    $y = reportItem($pdf, 'Mobile Friendly', ($tech['mobile_friendly'] ?? false) ? 'Da' : 'Ne', $y, ($tech['mobile_friendly'] ?? false) ? [52,211,153] : [248,113,113]);
    $y = reportItem($pdf, 'SSL Valid', ($tech['ssl_valid'] ?? false) ? 'Da' : 'Ne', $y, ($tech['ssl_valid'] ?? false) ? [52,211,153] : [248,113,113]);
    $y = reportItem($pdf, 'Google Analytics', ($tech['google_analytics'] ?? false) ? 'Da' : 'Ne', $y);
    $y = reportItem($pdf, 'Google Tag Manager', ($tech['google_tag_manager'] ?? false) ? 'Da' : 'Ne', $y);
    $y = reportItem($pdf, 'Cookie Consent', ($tech['cookie_consent'] ?? false) ? 'Da' : 'Ne', $y);
    $y = reportItem($pdf, 'Stevilo besed', (string)($tech['word_count'] ?? 0), $y);
    $y = reportItem($pdf, 'JS datoteke', (string)($tech['js_files'] ?? 0), $y);
    $y = reportItem($pdf, 'CSS datoteke', (string)($tech['css_files'] ?? 0), $y);
    $y = reportItem($pdf, 'Leto copyright', (string)($tech['copyright_year'] ?? 'N/A'), $y);
    $y = reportItem($pdf, 'Starost strani', ($tech['website_age_years'] ?? null) ? "{$tech['website_age_years']} let" : 'N/A', $y);
    $languages = implode(', ', $tech['languages'] ?? []);
    $y = reportItem($pdf, 'Jeziki (hreflang)', $languages ?: 'Noben', $y);
    
    // ═══ PAGE 3: SEO ANALYSIS ═══
    $y += 15;
    if ($y > 250) { $pdf->AddPage(); $pdf->SetFillColor(9,9,11); $pdf->Rect(0,0,210,297,'F'); $y = 20; }
    
    $y = sectionHeader($pdf, '3. SEO Analysis', $y);
    
    $seo = $audit['seo'] ?? [];
    $y = reportItem($pdf, 'Title', $seo['title'] ?? 'N/A', $y);
    $y = reportItem($pdf, 'Title dolzina', (string)($seo['title_length'] ?? 0) . ' znakov', $y, ($seo['title_optimal'] ?? false) ? [52,211,153] : [251,191,36]);
    $y = reportItem($pdf, 'Meta Description dolzina', (string)($seo['meta_length'] ?? 0) . ' znakov', $y, ($seo['meta_optimal'] ?? false) ? [52,211,153] : [251,191,36]);
    $y = reportItem($pdf, 'H1 oznake', (string)($seo['h1_count'] ?? 0), $y, ($seo['h1_count'] ?? 0) === 1 ? [52,211,153] : [248,113,113]);
    $y = reportItem($pdf, 'Skupno slik', (string)($seo['total_images'] ?? 0), $y);
    $y = reportItem($pdf, 'Slike brez alt', (string)($seo['images_without_alt'] ?? 0), $y, ($seo['images_without_alt'] ?? 0) === 0 ? [52,211,153] : [248,113,113]);
    $y = reportItem($pdf, 'Interni linki', (string)($seo['internal_links'] ?? 0), $y);
    $y = reportItem($pdf, 'Externi linki', (string)($seo['external_links'] ?? 0), $y);
    
    // ═══ CONTACT INFO ═══
    $y += 15;
    if ($y > 250) { $pdf->AddPage(); $pdf->SetFillColor(9,9,11); $pdf->Rect(0,0,210,297,'F'); $y = 20; }
    
    $y = sectionHeader($pdf, '4. Contact Information', $y);
    
    $contact = $audit['contact'] ?? [];
    $y = reportItem($pdf, 'Emaili', implode(', ', $contact['emails'] ?? []) ?: 'Noben', $y);
    $y = reportItem($pdf, 'Telefoni', implode(', ', $contact['phones'] ?? []) ?: 'Noben', $y);
    $y = reportItem($pdf, 'Socialna omrezja', implode(', ', $contact['social'] ?? []) ?: 'Noben', $y);
    
    // ═══ OPPORTUNITIES ═══
    $y += 15;
    if ($y > 250) { $pdf->AddPage(); $pdf->SetFillColor(9,9,11); $pdf->Rect(0,0,210,297,'F'); $y = 20; }
    
    $y = sectionHeader($pdf, '5. Opportunities & Recommendations', $y);
    
    $opps = $audit['opportunities'] ?? [];
    if (empty($opps)) {
        $y = reportItem($pdf, 'Ni tezav', 'Odlicno! Stran je dobro optimizirana.', $y, [52,211,153]);
    } else {
        foreach ($opps as $opp) {
            $priority = strtoupper($opp['priority']);
            $color = $opp['priority'] === 'high' ? [248,113,113] : ($opp['priority'] === 'medium' ? [251,191,36] : [160,160,170]);
            $y = reportItem($pdf, "[{$priority}]", $opp['reason'], $y, $color);
        }
    }
    
    // ═══ FINAL PAGE: NEXT STEPS ═══
    $pdf->AddPage();
    $pdf->SetFillColor(9, 9, 11);
    $pdf->Rect(0, 0, 210, 297, 'F');
    
    $y = sectionHeader($pdf, '6. Next Steps', 20);
    
    $steps = [
        ['1. Optimizirajte llms.txt', 'Datoteka llms.txt pove AI modelom kdo ste in kaj delajete. Brez nje ste nevidni.'],
        ['2. Dodajte Schema.org', 'Strukturirani podatki AI povedo kje ste, kaj delate, in kakšna so mnenja.'],
        ['3. Izboljšajte meta podatke', 'Title in meta description naj bosta jasna, relevantna in dolga 120-160 znakov.'],
        ['4. Zberite mnenja strank', 'Google Reviews so ključni za AI priporočila. Prosite zadovoljne stranke.'],
        ['5. Redno beležite napredek', 'Ponovno preverite čez 30 dni da vidite izboljšave.'],
    ];
    
    foreach ($steps as $step) {
        if ($y > 260) { $pdf->AddPage(); $pdf->SetFillColor(9,9,11); $pdf->Rect(0,0,210,297,'F'); $y = 20; }
        $pdf->SetXY(25, $y);
        $pdf->SetFont('Arial', 'B', 11);
        $pdf->SetTextColor(129, 140, 248);
        $pdf->Cell(170, 7, $step[0], 0, 1);
        $y += 7;
        $pdf->SetXY(30, $y);
        $pdf->SetFont('Arial', '', 10);
        $pdf->SetTextColor(180, 180, 190);
        $pdf->MultiCell(155, 5, $step[1]);
        $y = $pdf->GetY() + 8;
    }
    
    // CTA
    $y += 10;
    if ($y > 240) { $pdf->AddPage(); $pdf->SetFillColor(9,9,11); $pdf->Rect(0,0,210,297,'F'); $y = 20; }
    $pdf->SetXY(25, $y);
    $pdf->SetFont('Arial', 'B', 13);
    $pdf->SetTextColor(255, 255, 255);
    $pdf->Cell(170, 10, 'Zelite pomoc pri izboljsavi?', 0, 1);
    $y += 12;
    $pdf->SetXY(30, $y);
    $pdf->SetFont('Arial', '', 11);
    $pdf->SetTextColor(180, 180, 190);
    $pdf->MultiCell(155, 6, "Kontaktirajte nas: hercegdarko@hd-webdesign.si\nPonujamo AI Authority paket (€699 + €49/mesec)\nki poskrbi za vse zgoraj našteto.");
    
    // Final footer
    $pdf->SetXY(20, 270);
    $pdf->SetFont('Arial', '', 8);
    $pdf->SetTextColor(80, 80, 90);
    $pdf->Cell(170, 5, 'HD Web Design — hd-webdesign.si — AI Visibility Tool', 0, 1);
    $pdf->Cell(170, 5, date('Y-m-d H:i') . ' | This report is for internal use only.', 0, 1);
    
    // Save
    $path = sys_get_temp_dir() . "/ai-report-full-{$domain}-" . time() . ".pdf";
    $pdf->Output('F', $path);
    return $path;
}

// ═══ HELPERS ═══

function sectionHeader($pdf, $title, $y) {
    $pdf->SetXY(20, $y);
    $pdf->SetFont('Arial', 'B', 16);
    $pdf->SetTextColor(129, 140, 248);
    $pdf->Cell(170, 10, $title, 0, 1);
    // Accent line
    $pdf->SetFillColor(129, 140, 248);
    $pdf->Rect(20, $y + 11, 40, 1.5, 'F');
    return $y + 18;
}

function reportItem($pdf, $label, $value, $y, $color = null) {
    if ($y > 275) {
        $pdf->AddPage();
        $pdf->SetFillColor(9, 9, 11);
        $pdf->Rect(0, 0, 210, 297, 'F');
        $y = 20;
    }
    
    $pdf->SetXY(25, $y);
    $pdf->SetFont('Arial', '', 10);
    $pdf->SetTextColor(180, 180, 190);
    $pdf->Cell(70, 6, $label, 0, 0);
    
    if ($color) {
        $pdf->SetTextColor($color[0], $color[1], $color[2]);
    } else {
        $pdf->SetTextColor(255, 255, 255);
    }
    $pdf->SetFont('Arial', '', 10);
    
    // Truncate long values
    if (strlen($value) > 80) $value = substr($value, 0, 77) . '...';
    $pdf->Cell(95, 6, $value, 0, 1);
    
    return $y + 7;
}

function runAudit($domain) {
    $base = "https://{$domain}";
    $timeout = 8;
    
    function fetch_url($url, $timeout = 8) {
        $ch = curl_init();
        curl_setopt_array($ch, [
            CURLOPT_URL => $url,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT => $timeout,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_MAXREDIRS => 3,
            CURLOPT_USERAGENT => 'Mozilla/5.0 (compatible; AIVisibilityBot/1.0)',
        ]);
        $response = curl_exec($ch);
        $info = curl_getinfo($ch);
        curl_close($ch);
        return ['status' => $info['http_code'], 'body' => $response, 'ok' => $info['http_code'] >= 200 && $info['http_code'] < 400];
    }
    
    $result = [
        'domain' => $domain,
        'score' => 0,
        'checks' => [],
        'technical' => [],
        'seo' => [],
        'contact' => [],
        'opportunities' => [],
    ];
    
    // 1. Main page
    $main = fetch_url($base, $timeout);
    $result['checks']['main'] = ['pass' => $main['ok'], 'label' => 'Dostopnost strani', 'points' => 5];
    if ($main['ok']) $result['score'] += 5;
    $body = $main['body'];
    
    // 2. llms.txt
    $llms = fetch_url("{$base}/llms.txt", $timeout);
    $llms_pass = $llms['ok'] && strlen($llms['body']) > 50;
    $result['checks']['llms'] = ['pass' => $llms_pass, 'label' => 'llms.txt', 'points' => 30];
    if ($llms_pass) $result['score'] += 30;
    
    // 3. Schema.org
    preg_match_all('/<script[^>]+type=["\']application\/ld\+json["\'][^>]*>(.*?)<\/script>/si', $body, $schema_matches);
    $has_schema = !empty($schema_matches[1]);
    $result['checks']['schema'] = ['pass' => $has_schema, 'label' => 'Schema.org', 'points' => 25];
    if ($has_schema) $result['score'] += 25;
    
    // 4. Meta description
    preg_match('/<meta[^>]+name=["\']description["\'][^>]+content=["\']([^"\']*)["\']/i', $body, $meta_match);
    $has_meta = !empty($meta_match[1]) && strlen($meta_match[1]) > 20;
    $result['checks']['meta'] = ['pass' => $has_meta, 'label' => 'Meta description', 'points' => 15];
    if ($has_meta) $result['score'] += 15;
    
    // 5. Open Graph
    preg_match('/<meta[^>]+property=["\']og:title["\']/i', $body, $og_title);
    preg_match('/<meta[^>]+property=["\']og:description["\']/i', $body, $og_desc);
    $has_og = !empty($og_title[0]) && !empty($og_desc[0]);
    $result['checks']['og'] = ['pass' => $has_og, 'label' => 'Open Graph', 'points' => 10];
    if ($has_og) $result['score'] += 10;
    
    // 6. Sitemap
    $sitemap = fetch_url("{$base}/sitemap.xml", $timeout);
    $result['checks']['sitemap'] = ['pass' => $sitemap['ok'], 'label' => 'Sitemap.xml', 'points' => 10];
    if ($sitemap['ok']) $result['score'] += 10;
    
    // 7. Robots.txt
    $robots = fetch_url("{$base}/robots.txt", $timeout);
    $result['checks']['robots'] = ['pass' => $robots['ok'], 'label' => 'Robots.txt', 'points' => 5];
    if ($robots['ok']) $result['score'] += 5;
    
    // Grade
    if ($result['score'] >= 70) $result['grade'] = 'A';
    elseif ($result['score'] >= 50) $result['grade'] = 'B';
    elseif ($result['score'] >= 30) $result['grade'] = 'C';
    elseif ($result['score'] >= 10) $result['grade'] = 'D';
    else $result['grade'] = 'F';
    
    // Technical
    $result['technical']['https'] = (strpos($base, 'https://') === 0);
    $result['technical']['mobile_friendly'] = (strpos($body, 'viewport') !== false);
    $result['technical']['google_analytics'] = (preg_match('/G-[A-Z0-9]+|UA-[0-9]+|gtag|googletagmanager/i', $body) > 0);
    $result['technical']['google_tag_manager'] = (strpos($body, 'googletagmanager.com/gtm') !== false);
    $result['technical']['cookie_consent'] = (preg_match('/cookie|consent|gdpr|privacy.*policy/i', $body) > 0);
    $result['technical']['word_count'] = str_word_count(strip_tags(preg_replace('/\s+/', ' ', $body)));
    
    $cms = 'unknown';
    if (preg_match('/wp-content|wordpress/i', $body)) $cms = 'WordPress';
    elseif (preg_match('/wix\.com|wixstatic/i', $body)) $cms = 'Wix';
    elseif (preg_match('/squarespace/i', $body)) $cms = 'Squarespace';
    elseif (preg_match('/shopify/i', $body)) $cms = 'Shopify';
    $result['technical']['cms'] = $cms;
    
    preg_match('/<title>(.*?)<\/title>/si', $body, $title_match);
    $result['seo']['title'] = strip_tags($title_match[1] ?? '');
    $result['seo']['title_length'] = strlen($result['seo']['title']);
    $result['seo']['title_optimal'] = $result['seo']['title_length'] >= 30 && $result['seo']['title_length'] <= 60;
    
    preg_match('/<meta[^>]+name=["\']description["\'][^>]+content=["\']([^"\']*)["\']/i', $body, $desc_match);
    $result['seo']['meta_length'] = strlen($desc_match[1] ?? '');
    $result['seo']['meta_optimal'] = $result['seo']['meta_length'] >= 120 && $result['seo']['meta_length'] <= 160;
    
    preg_match_all('/<h1[^>]*>(.*?)<\/h1>/si', $body, $h1s);
    $result['seo']['h1_count'] = count($h1s[0]);
    
    preg_match_all('/<img[^>]+>/i', $body, $imgs);
    $no_alt = 0;
    foreach ($imgs[0] as $img) {
        if (!preg_match('/alt=["\'][^"\']+["\']/', $img)) $no_alt++;
    }
    $result['seo']['total_images'] = count($imgs[0]);
    $result['seo']['images_without_alt'] = $no_alt;
    
    preg_match_all('/href=["\']https?:\/\/([^"\']*)["\']/i', $body, $all_links);
    $internal = 0; $external = 0;
    foreach ($all_links[1] as $link) {
        if (strpos($link, $domain) !== false) $internal++;
        else $external++;
    }
    $result['seo']['internal_links'] = $internal;
    $result['seo']['external_links'] = $external;
    
    // Contact
    preg_match_all('/mailto:([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})/i', $body, $emails);
    $result['contact']['emails'] = array_unique($emails[1]);
    
    preg_match_all('/tel:([+0-9\s-]+)/i', $body, $phones);
    $result['contact']['phones'] = array_unique(array_map('trim', $phones[1]));
    
    $social_patterns = [
        'facebook' => '/facebook\.com\/([^"\'?\s]+)/i',
        'instagram' => '/instagram\.com\/([^"\'?\s]+)/i',
        'linkedin' => '/linkedin\.com\/(company|in)\/([^"\'?\s]+)/i',
    ];
    $result['contact']['social'] = [];
    foreach ($social_patterns as $name => $pattern) {
        if (preg_match($pattern, $body, $m)) {
            $result['contact']['social'][] = $name;
        }
    }
    
    // Opportunities
    $opps = [];
    if (!$has_schema) $opps[] = ['type' => 'ai_authority', 'priority' => 'high', 'reason' => 'Nimajo Schema.org — AI modeli ne razumejo strukture'];
    if (!$llms_pass) $opps[] = ['type' => 'ai_authority', 'priority' => 'high', 'reason' => 'Nimajo llms.txt — AI ne ve kdo ste in kaj delate'];
    if ($no_alt > 0) $opps[] = ['type' => 'seo', 'priority' => 'medium', 'reason' => "{$no_alt} slik brez alt tagov"];
    if (!$result['technical']['cookie_consent']) $opps[] = ['type' => 'compliance', 'priority' => 'low', 'reason' => 'Ni vidnega GDPR consent-a'];
    if ($result['technical']['word_count'] < 300) $opps[] = ['type' => 'content', 'priority' => 'medium', 'reason' => "Samo {$result['technical']['word_count']} besed — malo vsebine za SEO"];
    if ($result['seo']['h1_count'] === 0) $opps[] = ['type' => 'seo', 'priority' => 'high', 'reason' => 'Ni H1 oznake'];
    $result['opportunities'] = $opps;
    
    return $result;
}
